import fs from 'node:fs';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';

// Load zlib globals (deflateRaw/inflateRaw) needed by cso.js
const require = createRequire(import.meta.url);
require('../vendor/zlib.cjs');

import {
  parseHeader, writeHeader, readIndex, HEADER_SIZE,
  decompressToISO, compressFromISO, transcompress,
} from '../cso/cso.js';

// Shared synthetic ISO fixture (generated by scripts/generate-e2e-fixture.js)
const testISO = new Uint8Array(fs.readFileSync('test/fixtures/test.iso'));

// MockFile: same pattern as compress-blocks.test.js
class MockFile {
  constructor(data, name = 'test.bin') {
    this._data = data instanceof Uint8Array ? data : new Uint8Array(data);
    this.name = name;
    this.size = this._data.length;
  }
  slice(start, end) {
    const sliced = this._data.slice(start, end);
    return {
      arrayBuffer: () => Promise.resolve(
        sliced.buffer.slice(sliced.byteOffset, sliced.byteOffset + sliced.byteLength)
      ),
    };
  }
}

describe('parseHeader / writeHeader round-trip', () => {
  it('round-trips header fields', () => {
    const header = writeHeader('CISO', 1234567890, 2048, 2);
    const parsed = parseHeader(header);
    assert.equal(parsed.magic, 'CISO');
    assert.equal(parsed.headerSize, 0x18);
    assert.equal(parsed.uncompressedSize, 1234567890);
    assert.equal(parsed.blockSize, 2048);
    assert.equal(parsed.version, 1);
    assert.equal(parsed.indexShift, 2);
  });

  it('round-trips ZISO header', () => {
    const header = writeHeader('ZISO', 9876543210, 2048, 0);
    const parsed = parseHeader(header);
    assert.equal(parsed.magic, 'ZISO');
    assert.equal(parsed.uncompressedSize, 9876543210);
    assert.equal(parsed.indexShift, 0);
  });
});

describe('readIndex', () => {
  it('reads index entries from buffer', () => {
    // Build a buffer with header + 3 index entries
    const header = writeHeader('CISO', 6144, 2048, 0);
    const count = 3;
    const buf = new Uint8Array(HEADER_SIZE + count * 4);
    buf.set(header, 0);
    const dv = new DataView(buf.buffer);
    dv.setUint32(HEADER_SIZE + 0, 100, true);
    dv.setUint32(HEADER_SIZE + 4, 200 | 0x80000000, true);  // uncompressed flag
    dv.setUint32(HEADER_SIZE + 8, 300, true);

    const index = readIndex(buf, count);
    assert.equal(index[0], 100);
    assert.equal(index[1], (200 | 0x80000000) >>> 0);
    assert.equal(index[2], 300);
  });
});

describe('ISO -> CSO -> ISO round-trip', () => {
  it('byte-compares after round-trip (32KB synthetic ISO)', async () => {
    const isoFile = new MockFile(testISO, 'test.iso');

    const cso = await compressFromISO(isoFile, 'CSO');
    assert.ok(cso.length > 0, 'CSO output should not be empty');

    // Verify CSO header
    const header = parseHeader(cso.slice(0, HEADER_SIZE));
    assert.equal(header.magic, 'CISO');
    assert.equal(header.uncompressedSize, testISO.length);

    const csoFile = new MockFile(cso, 'test.cso');
    const result = await decompressToISO(csoFile);
    assert.equal(result.length, testISO.length, 'Decompressed size must match');
    assert.deepStrictEqual(Array.from(result), Array.from(testISO), 'Data must match');
  });
});

describe('ISO -> ZSO -> ISO round-trip', () => {
  it('byte-compares after round-trip (32KB synthetic ISO)', async () => {
    const isoFile = new MockFile(testISO, 'test.iso');

    const zso = await compressFromISO(isoFile, 'ZSO');
    assert.ok(zso.length > 0, 'ZSO output should not be empty');

    const header = parseHeader(zso.slice(0, HEADER_SIZE));
    assert.equal(header.magic, 'ZISO');
    assert.equal(header.uncompressedSize, testISO.length);

    const zsoFile = new MockFile(zso, 'test.zso');
    const result = await decompressToISO(zsoFile);
    assert.equal(result.length, testISO.length, 'Decompressed size must match');
    assert.deepStrictEqual(Array.from(result), Array.from(testISO), 'Data must match');
  });
});

describe('CSO -> ZSO transcompression -> ISO round-trip', () => {
  it('byte-compares original ISO after CSO->ZSO->ISO', async () => {
    const isoFile = new MockFile(testISO, 'test.iso');

    // ISO -> CSO
    const cso = await compressFromISO(isoFile, 'CSO');
    const csoFile = new MockFile(cso, 'test.cso');

    // CSO -> ZSO (transcompression)
    const zso = await transcompress(csoFile, 'CSO', 'ZSO');
    const zsoHeader = parseHeader(zso.slice(0, HEADER_SIZE));
    assert.equal(zsoHeader.magic, 'ZISO');

    // ZSO -> ISO
    const zsoFile = new MockFile(zso, 'test.zso');
    const result = await decompressToISO(zsoFile);
    assert.equal(result.length, testISO.length, 'Decompressed size must match');
    assert.deepStrictEqual(Array.from(result), Array.from(testISO), 'Data must match');
  });
});

describe('ZSO -> CSO transcompression -> ISO round-trip', () => {
  it('byte-compares original ISO after ZSO->CSO->ISO', async () => {
    const isoFile = new MockFile(testISO, 'test.iso');

    // ISO -> ZSO
    const zso = await compressFromISO(isoFile, 'ZSO');
    const zsoFile = new MockFile(zso, 'test.zso');

    // ZSO -> CSO (transcompression)
    const cso = await transcompress(zsoFile, 'ZSO', 'CSO');
    const csoHeader = parseHeader(cso.slice(0, HEADER_SIZE));
    assert.equal(csoHeader.magic, 'CISO');

    // CSO -> ISO
    const csoFile = new MockFile(cso, 'test.cso');
    const result = await decompressToISO(csoFile);
    assert.equal(result.length, testISO.length, 'Decompressed size must match');
    assert.deepStrictEqual(Array.from(result), Array.from(testISO), 'Data must match');
  });
});

describe('progress callback', () => {
  it('calls onProgress during compression', async () => {
    const isoFile = new MockFile(testISO, 'test.iso');
    const calls = [];
    await compressFromISO(isoFile, 'CSO', (pct, label) => calls.push({ pct, label }));
    assert.ok(calls.length > 0, 'Should have received progress callbacks');
    assert.equal(calls[calls.length - 1].pct, 1, 'Last progress should be 1');
  });
});
