#!/usr/bin/env node
// Generate vendor/xdelta3-inline.js from node_modules/xdelta3-wasm
//
// Instead of regex-patching the upstream JS bundle, we write our own clean
// wrapper around the same .wasm binary. The glue logic (malloc, memcpy,
// call xd3 function, read output) is simple and stable across versions.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const PKG = path.join(ROOT, 'node_modules', 'xdelta3-wasm', 'dist');

const wasmFile = fs.readdirSync(PKG).find(f => f.endsWith('.wasm'));
if (!wasmFile) throw new Error('No .wasm file found in xdelta3-wasm/dist');
const wasmB64 = fs.readFileSync(path.join(PKG, wasmFile)).toString('base64');

const wrapper = `// Auto-generated by scripts/vendor-xdelta3.js — do not edit
// Clean wrapper around xdelta3-wasm's compiled WASM binary.
// Exports: init, xd3_decode_memory, xd3_encode_memory

const WASM_B64 = '${wasmB64}';

let _w = null;

function decodeB64(b64) {
  if (typeof Buffer !== 'undefined') return Buffer.from(b64, 'base64');
  const raw = globalThis.atob(b64);
  const buf = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) buf[i] = raw.charCodeAt(i);
  return buf;
}

const _initPromise = WebAssembly.instantiate(decodeB64(WASM_B64), {}).then(w => { _w = w; });

export async function init() {
  await _initPromise;
}

function ex(name) {
  if (!_w) throw new Error('WASM not initialized — await init() first');
  return _w.instance.exports[name];
}

function writeToMemory(ptr, data) {
  new Uint8Array(ex('memory').buffer, ptr, data.byteLength).set(data);
}

function readFromMemory(ptr, length) {
  return new Uint8Array(ex('memory').buffer, ptr, length);
}

function readCStr(ptr) {
  const mem = ex('memory');
  const view = new DataView(mem.buffer);
  let end = ptr;
  while (view.getUint8(end) !== 0) end++;
  return new TextDecoder().decode(new Uint8Array(mem.buffer, ptr, end - ptr));
}

const WASI_ERRNO = { 0: 'SUCCESS', 48: 'ENOMEM', 51: 'ENOSPC' };

function getCodeStr(code) {
  if (code in WASI_ERRNO) return WASI_ERRNO[code];
  return readCStr(ex('xd3_strerror')(code));
}

function callXD3(fnName, input, source, outputMax, flags) {
  const malloc = ex('malloc'), free = ex('free');
  const mem = ex('memory');

  const inputPtr = malloc(input.byteLength);
  const sourcePtr = malloc(source.byteLength);
  const outputPtr = malloc(outputMax);
  const sizePtr = malloc(4);

  writeToMemory(inputPtr, input);
  writeToMemory(sourcePtr, source);

  const ret = ex(fnName)(inputPtr, input.byteLength, sourcePtr, source.byteLength, outputPtr, sizePtr, outputMax, flags);

  const outputSize = new DataView(mem.buffer).getUint32(sizePtr, true);
  const output = new Uint8Array(outputSize);
  output.set(readFromMemory(outputPtr, outputSize));

  free(inputPtr);
  free(sourcePtr);
  free(outputPtr);
  free(sizePtr);

  return { ret, str: getCodeStr(ret), output };
}

export function xd3_decode_memory(input, source, outputMax) {
  return callXD3('xd3_decode_memory', input, source, outputMax, 0);
}

export function xd3_encode_memory(input, source, outputMax, smatchCfg) {
  return callXD3('xd3_encode_memory', input, source, outputMax, smatchCfg || 0);
}
`;

const out = path.join(ROOT, 'vendor', 'xdelta3-inline.js');
fs.writeFileSync(out, wrapper);
console.log(`Wrote ${out} (${(fs.statSync(out).size / 1024).toFixed(1)} KB)`);
